### ISSUE TITLE
Feature request: A way to exclude certain words and/or phrases from the results.

### ISSUE THREAD

**Issue by easp** [N8python/rugpull#1]
I've been playing with RUGPULL. It's cool. Thanks for releasing it!

I converted some emergency procedures from work into a text file. In exploring things I realized that it would be useful to give it some guidance about words to ignore or avoid in the results.

To give a specific example, I wanted to see things that someone with the "emergency commander" role is tasked with. The results contain that information, but they also include many results where someone else is instructed to "update emergency commander." I'd like to exclude the latter and only show results that show the former. A common convention for expressing this in search interfaces is '-Word' and '-"multi-word phrase"'. Another is to have a separate field for "negative prompts."

**Comment by N8python** [comment]
Got it... perhaps the similarity could be computed as SIM_POSITIVE - SIM NEGATIVE, then.

**Comment by N8python** [comment]
@easp The latest release supports appending a "--no [negative prompt here]" flag to your query.
